enum ActionTypes {
    EVENT_CREATE = 'EVENT_CREATE',
    EVENTS_FETCH = 'EVENTS_FETCH',
    EVENT_DELETE = 'EVENT_DELETE',
    STREAKS_FETCH = 'STREAKS_FETCH',
    STREAK_SELECT = 'STREAK_SELECT',
    STREAK_CREATE = 'STREAK_CREATE',
    STREAK_DELETE = 'STREAK_DELETE',
    USERS_FETCH = 'USERS_FETCH'
}

export default ActionTypes;